<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="18" hostname="PINKYPRIYA" name="org.rerun.Employee" tests="23" failures="2" timestamp="04 Nov 2020 13:28:20 GMT" time="0.206" errors="0">
  <testcase name="test4" time="0.003" classname="org.rerun.Employee"/>
  <testcase name="test3" time="0.018" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.004" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.005" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.rerun.Employee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at org.rerun.Employee.test2(Employee.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.004" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.002" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.008" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.012" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.004" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test5" time="0.011" classname="org.rerun.Employee"/>
  <testcase name="test3" time="0.003" classname="org.rerun.Employee">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at org.rerun.Employee.test3(Employee.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.008" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.006" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.003" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.073" classname="org.rerun.Employee"/>
  <testcase name="test3" time="0.003" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.011" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.005" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.009" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.009" classname="org.rerun.Employee">
    <skipped/>
  </testcase> <!-- test3 -->
</testsuite> <!-- org.rerun.Employee -->
